### ISSUE TITLE
Measurement Calculation Error - Orbital Vector

### ISSUE THREAD

**Issue by crazyGru** [HarmonyAI09/face-beauty-frontend#33]
**Describe the bug**
It says positive when the eye clearly sits in front of the tissue underneath. The bottom point is behind the top eye. That is negative. So double check the math on that assessments because it is not correct.

**Screenshots**

![Image](https://github.com/HarmonyAI09/face-beauty-frontend/assets/137296569/b55d2896-1d21-446e-aa0c-7e9d6bce9225)

Updated still in error:
![Image](https://github.com/HarmonyAI09/face-beauty-frontend/assets/157229524/1e3f27fc-8d0f-4a55-ae01-eac9f58c623a)

![Image](https://github.com/HarmonyAI09/face-beauty-frontend/assets/157229524/aed1f0bb-f17a-418e-9681-2cd5c64f79ca)

**Comment by crazyGru** [comment]
I've fixed the code for Orbital Vector Calculation.

![Image](https://github.com/HarmonyAI09/face-beauty-frontend/assets/137296569/6e8f49cd-2504-4e3b-8424-83b1fc0b78e6)

**Comment by crazyGru** [comment]
![Image](https://github.com/HarmonyAI09/face-beauty-frontend/assets/137296569/7023d782-d16c-4203-92dc-db9a52d519cb)

Updated the code.

**Comment by DitmarHoxha** [comment]
Unless the code didnt update it is still showing wrong

![Image](https://github.com/HarmonyAI09/face-beauty-frontend/assets/157229524/10493498-c118-458a-b4b1-2be2ec00c5fa)
